### ISSUE TITLE
bug call-SubdivideSequence (minor bug, major effect)

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/reat#20]
There is a bug with the chunking for augustus (call-SubdivideSequence)

[should be `start = end + 1 - ~{overlap}`](https://github.com/EI-CoreBioinformatics/reat/blob/e66da9ed68810a12e16c9f1dcd88f0f5fe5e08a8/annotation/prediction_module/augustus.wdl#L345)

i.e. remove the +

Before the fix
This sequence generates the following chunks:
>Calendula_officinalis_EIV1.2_Contig_0000001:1-3000001
>Calendula_officinalis_EIV1.2_Contig_0000001:2900003-5900003
>Calendula_officinalis_EIV1.2_Contig_0000001:8700007-11700007
>Calendula_officinalis_EIV1.2_Contig_0000001:20300015-23300015
>Calendula_officinalis_EIV1.2_Contig_0000001:43500031-46500031
>Calendula_officinalis_EIV1.2_Contig_0000001:89900063-92900063
>Calendula_officinalis_EIV1.2_Contig_0000001:182700127-104728146

With the fix
>Calendula_officinalis_EIV1.2_Contig_0000001:1-3000001
>Calendula_officinalis_EIV1.2_Contig_0000001:2900002-5900002
>Calendula_officinalis_EIV1.2_Contig_0000001:5800003-8800003
>Calendula_officinalis_EIV1.2_Contig_0000001:8700004-11700004
>Calendula_officinalis_EIV1.2_Contig_0000001:11600005-14600005
>Calendula_officinalis_EIV1.2_Contig_0000001:14500006-17500006
>Calendula_officinalis_EIV1.2_Contig_0000001:17400007-20400007
>Calendula_officinalis_EIV1.2_Contig_0000001:20300008-23300008
>Calendula_officinalis_EIV1.2_Contig_0000001:23200009-26200009
>Calendula_officinalis_EIV1.2_Contig_0000001:26100010-29100010
>Calendula_officinalis_EIV1.2_Contig_0000001:29000011-32000011
>Calendula_officinalis_EIV1.2_Contig_0000001:31900012-34900012
>Calendula_officinalis_EIV1.2_Contig_0000001:34800013-37800013
>Calendula_officinalis_EIV1.2_Contig_0000001:37700014-40700014
>Calendula_officinalis_EIV1.2_Contig_0000001:40600015-43600015
>Calendula_officinalis_EIV1.2_Contig_0000001:43500016-46500016
>Calendula_officinalis_EIV1.2_Contig_0000001:46400017-49400017
>Calendula_officinalis_EIV1.2_Contig_0000001:49300018-52300018
>Calendula_officinalis_EIV1.2_Contig_0000001:52200019-55200019
>Calendula_officinalis_EIV1.2_Contig_0000001:55100020-58100020
>Calendula_officinalis_EIV1.2_Contig_0000001:58000021-61000021
>Calendula_officinalis_EIV1.2_Contig_0000001:60900022-63900022
>Calendula_officinalis_EIV1.2_Contig_0000001:63800023-66800023
>Calendula_officinalis_EIV1.2_Contig_0000001:66700024-69700024
>Calendula_officinalis_EIV1.2_Contig_0000001:69600025-72600025
>Calendula_officinalis_EIV1.2_Contig_0000001:72500026-75500026
>Calendula_officinalis_EIV1.2_Contig_0000001:75400027-78400027
>Calendula_officinalis_EIV1.2_Contig_0000001:78300028-81300028
>Calendula_officinalis_EIV1.2_Contig_0000001:81200029-84200029
>Calendula_officinalis_EIV1.2_Contig_0000001:84100030-87100030
>Calendula_officinalis_EIV1.2_Contig_0000001:87000031-90000031
>Calendula_officinalis_EIV1.2_Contig_0000001:89900032-92900032
>Calendula_officinalis_EIV1.2_Contig_0000001:92800033-95800033
>Calendula_officinalis_EIV1.2_Contig_0000001:95700034-98700034
>Calendula_officinalis_EIV1.2_Contig_0000001:98600035-101600035
>Calendula_officinalis_EIV1.2_Contig_0000001:101500036-104500036
>Calendula_officinalis_EIV1.2_Contig_0000001:104400037-104728146

**Comment by ljyanesm** [comment]
Fixed by 8ffc62b0

To install the changes on the HPC, go to the reat-dev_prediction path and then into the directory called ...prediction_branch... and run:

source reat-dev_prediction; git pull; pip install .
