### ISSUE TITLE
expose resources for call-OptimiseAugustus

### ISSUE THREAD

**Issue by swarbred** [EI-CoreBioinformatics/reat#28]
@ljyanesm @gemygk 
Hitting memory for the call-OptimiseAugustus step are the resources for this exposed?

**Comment by swarbred** [comment]
Note edited in the installed reat at (increased to 16G)
       https://github.com/EI-CoreBioinformatics/reat/blob/a6003c9b87cd8156fd644a0ea30211933196a34b/annotation/prediction_module/main.wdl#L852

Can expose or just simply increase to 16G for a permanent solution later

**Comment by ljyanesm** [comment]
Hi @swarbred,

Using the `--computational_resources` input. One can tune the call-OptimiseAugustus task cpu/memory by defining the required resources using the `"ei_prediction.OptimiseAugustus.resources"` parameter

**Comment by swarbred** [comment]
Thanks @ljyanesm

**Comment by swarbred** [comment]
yes this can be closed
