### ISSUE TITLE
How to cite REAT in a paper

### ISSUE THREAD

**Issue by dadrasarmin** [EI-CoreBioinformatics/reat#40]
Hi,

I used your tool and I want to cite it in our manuscript. I wanted to ask you how should I cite your work. I could not find any DOI or paper related to this tool. If you have a suggestion for how to cite reat, could you please write it somewhere on the documentation or on the Github page?
At the moment, I just used the link to this Github repo.

Best regards,
Armin

**Comment by swarbred** [comment]
Yes at the moment just cite the github repo

**Comment by dadrasarmin** [comment]
@swarbred, Thanks.
