### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by yuzhenpeng** [EI-CoreBioinformatics/reat#42]
Dear author, 

When I installed this software on my computer, I got an error warning.
Could you give me some suggestion.
```
$pip install ./reat/
Processing ./reat
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting 2passtools@ git+https://github.com/bartongroup/2passtools.git#d4378d0
  Cloning https://github.com/bartongroup/2passtools.git to /tmp/pip-install-kp6uo_p_/2passtools_98265f384cdc42daab3aaf786f9fdf76
  Running command git clone --filter=blob:none --quiet https://github.com/bartongroup/2passtools.git /tmp/pip-install-kp6uo_p_/2passtools_98265f384cdc42daab3aaf786f9fdf76
  fatal: unable to access 'https://github.com/bartongroup/2passtools.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/bartongroup/2passtools.git /tmp/pip-install-kp6uo_p_/2passtools_98265f384cdc42daab3aaf786f9fdf76 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/bartongroup/2passtools.git /tmp/pip-install-kp6uo_p_/2passtools_98265f384cdc42daab3aaf786f9fdf76 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Thank you,
Zhen-peng

**Comment by gemygk** [comment]
Dear @yuzhenpeng 

Thanks for reporting the issue and providing the error log.

Can you please check if you can access the GitHub link - https://github.com/bartongroup/2passtools.git?

As you can see in the above error log, it says:

> fatal: unable to access 'https://github.com/bartongroup/2passtools.git/': HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
> error: subprocess-exited-with-error

It looks like a `git config` issue.

Thanks,
Gemy

**Comment by yuzhenpeng** [comment]
Dear Gemy，

Thanks for your reply. It seems very well.
![image](https://user-images.githubusercontent.com/31943277/195164109-1d9a33fb-91b0-4fc7-8d14-7489cd688fa1.png)

**Comment by gemygk** [comment]
Dear @yuzhenpeng 

Thanks for testing it.

I have just tried to install `REAT` myself (in another location for testing using `--prefix`, please see below) and it works fine. I have used `mamba` to install dependencies a bit faster (I will update the documentation to use `mamba`)

```
$ cd /path/to/software
$ git clone git@github.com:EI-CoreBioinformatics/reat.git
$ wget https://github.com/broadinstitute/cromwell/releases/download/62/cromwell-62.jar
$ mamba env create -f reat/reat.yml --prefix /path/to/software/reat/x86_64
$ conda activate /path/to/software/reat/x86_64
(/path/to/software/reat/x86_64) $ pip install reat/
(/path/to/software/reat/x86_64) $ which reat
/path/to/software/reat/x86_64/bin/reat
(/path/to/software/reat/x86_64) $ reat --help
```

For reference, I am adding the `pip` 2passtools log below which works fine at our end and it should be similar when you try:

```
...
...
Collecting 2passtools@ git+https://github.com/bartongroup/2passtools.git#d4378d0
  Cloning https://github.com/bartongroup/2passtools.git to /tmp/pip-install-xpwzm_xv/2passtools_a1469f8bb1a34c4eb08433a62db13bfb
  Running command git clone --filter=blob:none --quiet https://github.com/bartongroup/2passtools.git /tmp/pip-install-xpwzm_xv/2passtools_a1469f8bb1a34c4eb08433a62db13bfb
  Resolved https://github.com/bartongroup/2passtools.git to commit d4378d0f4a780b5b89399161ed8eac6ca5092128
  Preparing metadata (setup.py) ... done
...
...
```

Can you please try the above steps and let me know how it goes?

Thanks,
Gemy

**Comment by yuzhenpeng** [comment]
Dear @gemygk,

Thanks for your kind help. I followed your new pipeline to install REAT.
Unfortunately, I got a new error warning shown as followed.

`Processing ./reat
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting 2passtools@ git+https://github.com/bartongroup/2passtools.git#d4378d0
  Cloning https://github.com/bartongroup/2passtools.git to /tmp/pip-install-1hofbgo8/2passtools_1b35d4d60c2c41caa7efd63e2936d30c
  Running command git clone --filter=blob:none --quiet https://github.com/bartongroup/2passtools.git /tmp/pip-install-1hofbgo8/2passtools_1b35d4d60c2c41caa7efd63e2936d30c
  Resolved https://github.com/bartongroup/2passtools.git to commit d4378d0f4a780b5b89399161ed8eac6ca5092128
  Preparing metadata (setup.py) ... done
Collecting parasail~=1.2.4
  Using cached parasail-1.2.4-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)
Requirement already satisfied: biopython~=1.78 in /root/data1/yuzhenpeng2021/miniconda3/envs/REAT/lib/python3.9/site-packages (from reat==0.6.1) (1.79)
Collecting jsonschema~=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting mikado~=2.3.0
  Using cached Mikado-2.3.4.tar.gz (24.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/root/data1/yuzhenpeng2021/miniconda3/envs/REAT/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/root/data1/yuzhenpeng2021/miniconda3/envs/REAT/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/data1/yuzhenpeng2021/miniconda3/envs/REAT/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-bj8uibuh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-bj8uibuh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-bj8uibuh/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
      ModuleNotFoundError: No module named 'scipy._build_utils'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by gemygk** [comment]
@yuzhenpeng 

Just came across a similar error with `pip` in StackOverflow - https://stackoverflow.com/q/71009659, and it was caused due the latest `pip` and `python 3.10`

May I know the version of `pip` you were using? 

I was using `pip 21.1.3` with `python 3.9.5`.

**Comment by yuzhenpeng** [comment]
Hi, @gemygk 

Thank your suggestion.
The version of `pip` and `python` on my computer are `Python 3.9.9` and `pip 22.2.2`.
![image](https://user-images.githubusercontent.com/31943277/195482586-8c077695-f788-4389-be51-68ff85b5b72a.png)

I run the command like you `pip install --no-cache-dir ./reat`.
But I still obtained an error `Getting requirements to build wheel ... error`.

I guess it may be the network problems, likely HTTPs/HTTP.

`Processing ./reat
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting 2passtools@ git+https://github.com/bartongroup/2passtools.git#d4378d0
  Cloning https://github.com/bartongroup/2passtools.git to /tmp/pip-install-g1coajy7/2passtools_809c5530699646a8821172e4e7740967
  Running command git clone --filter=blob:none --quiet https://github.com/bartongroup/2passtools.git /tmp/pip-install-g1coajy7/2passtools_809c5530699646a8821172e4e7740967
  Resolved https://github.com/bartongroup/2passtools.git to commit d4378d0f4a780b5b89399161ed8eac6ca5092128
  Preparing metadata (setup.py) ... done
Collecting pyyaml~=5.4.1
  Downloading PyYAML-5.4.1-cp39-cp39-manylinux1_x86_64.whl (630 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 630.1/630.1 kB 804.7 kB/s eta 0:00:00
Collecting jsonschema~=3.2.0
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 kB 7.9 MB/s eta 0:00:00
Collecting pyfaidx~=0.5.8
  Downloading pyfaidx-0.5.9.5.tar.gz (32 kB)
  Preparing metadata (setup.py) ... done
Collecting parasail~=1.2.4
  Downloading parasail-1.2.4-py2.py3-none-manylinux2010_x86_64.whl (14.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 4.2 MB/s eta 0:00:00
Requirement already satisfied: biopython~=1.78 in ./reat/x86_64/lib/python3.9/site-packages (from reat==0.6.1) (1.79)
Collecting mikado~=2.3.0
  Downloading Mikado-2.3.4.tar.gz (24.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.7/24.7 MB 4.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/root/data1/yuzhenpeng2021/biosoft/reat/x86_64/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/root/data1/yuzhenpeng2021/biosoft/reat/x86_64/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/data1/yuzhenpeng2021/biosoft/reat/x86_64/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-32h_44jl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-32h_44jl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-32h_44jl/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
      ModuleNotFoundError: No module named 'scipy._build_utils'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by gemygk** [comment]
@yuzhenpeng 

My suggestion would be to downgrade `pip` and give it a go

```
pip install pip==21.3.1
```

**Comment by yuzhenpeng** [comment]
> @yuzhenpeng
> 
> My suggestion would be to downgrade `pip` and give it a go
> 
> ```
> pip install pip==21.3.1
> ```

Thank you for your suggestion. 

I set the pip mirror.
`pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple`

Now, it worked very well.

Thank you.

**Comment by gemygk** [comment]
Thanks @yuzhenpeng 

I am marking the issue as closed.

Please let us know if you have any queries.

**Comment by dadrasarmin** [comment]
Hi,

We had a similar problem. The solution suggested here could not solve the problem:
```
pip install pip==21.3.1
```
But, we have changed something in the `setup.py` file according to the Mikado Github page and it worked:
```
'mikado @ git+https://github.com/EI-CoreBioinformatics/mikado@fix_install'
```
Also, we fixed the python and pip version in the `reat.yml` as follows:
```
- pip=21.3.1
- python=3.9.9
```
After these changes, this command successfully installed reat:
```
pip install --no-cache-dir ./reat
```
It was tested on a Debian machine, and dependencies were installed via mamba.
